### ISSUE TITLE
Button Issues on Pending Approvals

### ISSUE THREAD

**Issue by mrjarbenne** [r-a-y/bp-site-moderation#3]
Just a small issue with the buttons beside a pending blog. The "visit site" button goes to the users profile instead, and the Approve and Deny buttons are floating a bit off-kilter: 

![2019-10-08_19-28-32](https://user-images.githubusercontent.com/480667/66440834-5fd2de80-ea02-11e9-95ed-0ee6c8b6ab53.png)

**Comment by r-a-y** [comment]
The "Visit Site" button having the wrong link is a Nouveau problem.

I would recommend getting rid of the "Visit Site" button since we already output the link after the "Created by X" line.  Let me know what you think.

**Comment by mrjarbenne** [comment]
I’m good with that.

**Comment by r-a-y** [comment]
The "Visit Site" button has been removed.

I encountered a minor bug when removing the button.  Just posted a ticket about this here - https://buddypress.trac.wordpress.org/ticket/8147
