### ISSUE TITLE
Dialogue After Site Submission is Misleading

### ISSUE THREAD

**Issue by mrjarbenne** [r-a-y/bp-site-moderation#4]
Could the text when a site submission goes through reflect that the site is pending moderation, and should be available soon? 

![2019-10-08_19-28-01](https://user-images.githubusercontent.com/480667/66440902-a6283d80-ea02-11e9-82ae-fa99a79569e2.png)

Your site request has been submitted and will be reviewed shortly. While you wait, why not update your avatar (link to profile) or explore some recent blog posts (link to activity feed)

**Comment by r-a-y** [comment]
This broke since BuddyPress 2.6 changed the site submission text.  Should be fixed now.
